// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBP_G4IoiXVYUtzd_XO4whFwNClPHhjJs',
    appId: '1:637322825771:web:2742b4179fe49e85f49a6e',
    messagingSenderId: '637322825771',
    projectId: 'fyp-farmtabai',
    authDomain: 'fyp-farmtabai.firebaseapp.com',
    storageBucket: 'fyp-farmtabai.firebasestorage.app',
    measurementId: 'G-3ZYFDC7XEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADK9ntI49jM3k5oxVUO6tAFT2U6aMwb28',
    appId: '1:637322825771:android:0a15d01662690085f49a6e',
    messagingSenderId: '637322825771',
    projectId: 'fyp-farmtabai',
    storageBucket: 'fyp-farmtabai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-5GfXxDL1UCZR2HJiqcxAav-nvhf-OxU',
    appId: '1:637322825771:ios:f852be2ed476c488f49a6e',
    messagingSenderId: '637322825771',
    projectId: 'fyp-farmtabai',
    storageBucket: 'fyp-farmtabai.firebasestorage.app',
    iosBundleId: 'com.example.farmtabAiFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-5GfXxDL1UCZR2HJiqcxAav-nvhf-OxU',
    appId: '1:637322825771:ios:f852be2ed476c488f49a6e',
    messagingSenderId: '637322825771',
    projectId: 'fyp-farmtabai',
    storageBucket: 'fyp-farmtabai.firebasestorage.app',
    iosBundleId: 'com.example.farmtabAiFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBP_G4IoiXVYUtzd_XO4whFwNClPHhjJs',
    appId: '1:637322825771:web:687e602a170d912bf49a6e',
    messagingSenderId: '637322825771',
    projectId: 'fyp-farmtabai',
    authDomain: 'fyp-farmtabai.firebaseapp.com',
    storageBucket: 'fyp-farmtabai.firebasestorage.app',
    measurementId: 'G-STQ9VDSLVZ',
  );
}
